POST http://localhost:4002/products
content-type: application/json

{
    "name": "Valorant",
    "price": 5
}

###

GET http://localhost:4002/products

###
GET http://localhost:4002/products/8c3fcf29-943d-4da5-b64e-1dc30a88f97e


###
PUT http://localhost:4002/products/778b9774-7c61-4b7e-bba3-23a519c4df89
content-type: application/json

{
    "name": "Minecraft",
    "price": 10
}

###
DELETE http://localhost:4002/products/744b0ea0-9ab8-44eb-be34-7e62cbfd9881