POST http://localhost:4002/products
content-type: application/json

{
    "name": "WarZone",
    "price": 99
}

###

GET http://localhost:4002/products

###
GET http://localhost:4002/products/8c3fcf29-943d-4da5-b64e-1dc30a88f97e


###
PUT http://localhost:4002/products/7840b6ef-6674-493f-a424-cdf9dad42c5c
content-type: application/json

{
    "name": "Rainbow Six",
    "price": 6
}

###
DELETE http://localhost:4002/products/3fb97bde-4608-42d0-b3b3-f5b8b6af9bb4